package com.dremio.exec.store.jdbc.conf;

import java.sql.*;
import java.util.Map;
import java.util.Properties;
import java.util.concurrent.Executor;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 * A standalone JDBC Connection implementation for LDAP using JNDI.
 *
 * This completely replaces the Octetstring JDBC-LDAP driver with a pure JNDI
 * implementation. No external LDAP JDBC driver JAR is needed.
 */
public class JndiLdapConnection implements Connection {
    private static final Logger LOG = Logger.getLogger(JndiLdapConnection.class.getName());

    private final String ldapUrl;
    private final String baseDN;
    private final String principal;
    private final String credentials;
    private final String[] objectClasses;
    private final String[] attributes;
    private final int maxRows;
    private final boolean useObjectCategory;
    private final boolean skipFilter;

    private boolean closed = false;
    private boolean autoCommit = true;
    private boolean readOnly = true;
    private String catalog = "";
    private String schema = "";

    public JndiLdapConnection(String ldapUrl, String baseDN, String principal, String credentials,
            String[] objectClasses, String[] attributes, int maxRows,
            boolean useObjectCategory, boolean skipFilter) {
        this.ldapUrl = ldapUrl;
        this.baseDN = baseDN;
        this.principal = principal;
        this.credentials = credentials;
        this.objectClasses = objectClasses;
        this.attributes = attributes;
        this.maxRows = maxRows;
        this.useObjectCategory = useObjectCategory;
        this.skipFilter = skipFilter;

        LOG.log(Level.INFO, "JndiLdapConnection created: " + ldapUrl + "/" + baseDN);
    }

    // Getters for use by metadata
    public String getLdapUrl() { return ldapUrl; }
    public String getBaseDN() { return baseDN; }
    public String getPrincipal() { return principal; }
    public String[] getObjectClasses() { return objectClasses; }
    public String[] getAttributes() { return attributes; }

    @Override
    public Statement createStatement() throws SQLException {
        checkClosed();
        return new JndiLdapStatement(this, ldapUrl, baseDN, principal, credentials,
                objectClasses, attributes, maxRows, useObjectCategory, skipFilter);
    }

    @Override
    public Statement createStatement(int resultSetType, int resultSetConcurrency) throws SQLException {
        return createStatement();
    }

    @Override
    public Statement createStatement(int resultSetType, int resultSetConcurrency, int resultSetHoldability) throws SQLException {
        return createStatement();
    }

    @Override
    public PreparedStatement prepareStatement(String sql) throws SQLException {
        throw new SQLFeatureNotSupportedException("PreparedStatement not supported for LDAP");
    }

    @Override
    public PreparedStatement prepareStatement(String sql, int resultSetType, int resultSetConcurrency) throws SQLException {
        throw new SQLFeatureNotSupportedException("PreparedStatement not supported for LDAP");
    }

    @Override
    public PreparedStatement prepareStatement(String sql, int resultSetType, int resultSetConcurrency, int resultSetHoldability) throws SQLException {
        throw new SQLFeatureNotSupportedException("PreparedStatement not supported for LDAP");
    }

    @Override
    public PreparedStatement prepareStatement(String sql, int autoGeneratedKeys) throws SQLException {
        throw new SQLFeatureNotSupportedException("PreparedStatement not supported for LDAP");
    }

    @Override
    public PreparedStatement prepareStatement(String sql, int[] columnIndexes) throws SQLException {
        throw new SQLFeatureNotSupportedException("PreparedStatement not supported for LDAP");
    }

    @Override
    public PreparedStatement prepareStatement(String sql, String[] columnNames) throws SQLException {
        throw new SQLFeatureNotSupportedException("PreparedStatement not supported for LDAP");
    }

    @Override
    public CallableStatement prepareCall(String sql) throws SQLException {
        throw new SQLFeatureNotSupportedException("CallableStatement not supported for LDAP");
    }

    @Override
    public CallableStatement prepareCall(String sql, int resultSetType, int resultSetConcurrency) throws SQLException {
        throw new SQLFeatureNotSupportedException("CallableStatement not supported for LDAP");
    }

    @Override
    public CallableStatement prepareCall(String sql, int resultSetType, int resultSetConcurrency, int resultSetHoldability) throws SQLException {
        throw new SQLFeatureNotSupportedException("CallableStatement not supported for LDAP");
    }

    @Override
    public String nativeSQL(String sql) throws SQLException {
        return sql;
    }

    // Transaction methods - LDAP doesn't support transactions
    @Override
    public void setAutoCommit(boolean autoCommit) throws SQLException {
        this.autoCommit = autoCommit;
    }

    @Override
    public boolean getAutoCommit() throws SQLException {
        return autoCommit;
    }

    @Override
    public void commit() throws SQLException {
        // No-op - LDAP doesn't support transactions
    }

    @Override
    public void rollback() throws SQLException {
        // No-op - LDAP doesn't support transactions
    }

    @Override
    public void rollback(Savepoint savepoint) throws SQLException {
        // No-op
    }

    @Override
    public Savepoint setSavepoint() throws SQLException {
        throw new SQLFeatureNotSupportedException("Savepoints not supported for LDAP");
    }

    @Override
    public Savepoint setSavepoint(String name) throws SQLException {
        throw new SQLFeatureNotSupportedException("Savepoints not supported for LDAP");
    }

    @Override
    public void releaseSavepoint(Savepoint savepoint) throws SQLException {
        throw new SQLFeatureNotSupportedException("Savepoints not supported for LDAP");
    }

    @Override
    public void setTransactionIsolation(int level) throws SQLException {
        // Ignore - LDAP doesn't support transaction isolation
    }

    @Override
    public int getTransactionIsolation() throws SQLException {
        return Connection.TRANSACTION_NONE;
    }

    @Override
    public void close() throws SQLException {
        closed = true;
    }

    @Override
    public boolean isClosed() throws SQLException {
        return closed;
    }

    private void checkClosed() throws SQLException {
        if (closed) {
            throw new SQLException("Connection is closed");
        }
    }

    @Override
    public DatabaseMetaData getMetaData() throws SQLException {
        return new JndiLdapDatabaseMetaData(this);
    }

    @Override
    public void setReadOnly(boolean readOnly) throws SQLException {
        this.readOnly = readOnly;
    }

    @Override
    public boolean isReadOnly() throws SQLException {
        return readOnly;
    }

    @Override
    public void setCatalog(String catalog) throws SQLException {
        this.catalog = catalog;
    }

    @Override
    public String getCatalog() throws SQLException {
        return catalog;
    }

    @Override
    public SQLWarning getWarnings() throws SQLException {
        return null;
    }

    @Override
    public void clearWarnings() throws SQLException {
    }

    @Override
    public Map<String, Class<?>> getTypeMap() throws SQLException {
        return null;
    }

    @Override
    public void setTypeMap(Map<String, Class<?>> map) throws SQLException {
    }

    @Override
    public void setHoldability(int holdability) throws SQLException {
    }

    @Override
    public int getHoldability() throws SQLException {
        return ResultSet.HOLD_CURSORS_OVER_COMMIT;
    }

    @Override
    public Clob createClob() throws SQLException {
        throw new SQLFeatureNotSupportedException();
    }

    @Override
    public Blob createBlob() throws SQLException {
        throw new SQLFeatureNotSupportedException();
    }

    @Override
    public NClob createNClob() throws SQLException {
        throw new SQLFeatureNotSupportedException();
    }

    @Override
    public SQLXML createSQLXML() throws SQLException {
        throw new SQLFeatureNotSupportedException();
    }

    @Override
    public boolean isValid(int timeout) throws SQLException {
        return !closed;
    }

    @Override
    public void setClientInfo(String name, String value) throws SQLClientInfoException {
    }

    @Override
    public void setClientInfo(Properties properties) throws SQLClientInfoException {
    }

    @Override
    public String getClientInfo(String name) throws SQLException {
        return null;
    }

    @Override
    public Properties getClientInfo() throws SQLException {
        return new Properties();
    }

    @Override
    public Array createArrayOf(String typeName, Object[] elements) throws SQLException {
        throw new SQLFeatureNotSupportedException();
    }

    @Override
    public Struct createStruct(String typeName, Object[] attributes) throws SQLException {
        throw new SQLFeatureNotSupportedException();
    }

    @Override
    public void setSchema(String schema) throws SQLException {
        this.schema = schema;
    }

    @Override
    public String getSchema() throws SQLException {
        return schema;
    }

    @Override
    public void abort(Executor executor) throws SQLException {
        close();
    }

    @Override
    public void setNetworkTimeout(Executor executor, int milliseconds) throws SQLException {
    }

    @Override
    public int getNetworkTimeout() throws SQLException {
        return 0;
    }

    @Override
    public <T> T unwrap(Class<T> iface) throws SQLException {
        if (iface.isInstance(this)) {
            return iface.cast(this);
        }
        throw new SQLException("Cannot unwrap to " + iface);
    }

    @Override
    public boolean isWrapperFor(Class<?> iface) throws SQLException {
        return iface.isInstance(this);
    }
}
